// Divine Power: resource pool gating god-hand actions.
// Generated by followers, spent on interventions.

import { CultStance } from '../components/Zealotry';

export interface DivinePowerState {
  power: number;
  maxPower: number;
  generationRate: number;  // per-tick rate (computed)
  followerCount: number;
  devoteeCount: number;
  terrorCount: number;
  aweCount: number;
  rebelCount: number;
  totalSpent: number;
  totalGenerated: number;
}

// Costs
export const POWER_COST_PICKUP = 5;
export const POWER_COST_BIOME_CHANGE = 2;

export function createDivinePower(): DivinePowerState {
  return {
    power: 0,
    maxPower: 10,
    generationRate: 0,
    followerCount: 0,
    devoteeCount: 0,
    terrorCount: 0,
    aweCount: 0,
    rebelCount: 0,
    totalSpent: 0,
    totalGenerated: 0,
  };
}

/** Spend power; returns true if affordable */
export function spendPower(dp: DivinePowerState, cost: number): boolean {
  if (dp.power < cost) return false;
  dp.power -= cost;
  dp.totalSpent += cost;
  return true;
}

/** Add generated power */
export function addPower(dp: DivinePowerState, amount: number): void {
  dp.power = Math.min(dp.power + amount, dp.maxPower * 1.5); // soft cap 150%
  dp.totalGenerated += amount;
}

/** Update soft cap & overflow decay */
export function updatePowerCap(dp: DivinePowerState): void {
  dp.maxPower = 10 + dp.followerCount * 2 + dp.devoteeCount * 3;
  // Overflow decay
  if (dp.power > dp.maxPower) {
    dp.power -= (dp.power - dp.maxPower) * 0.01;
  }
}
